sudo: required
dist: trusty
addons:
  firefox: "latest"
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '6'
cache:
- node_modules
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install -g lerna
- git clone https://github.com/ckeditor/ckeditor5-dev.git
- cd ckeditor5-dev && git checkout t/ckeditor5/615 && lerna bootstrap && cd packages/ckeditor5-dev-tests && npm link && cd ../../../
- npm link @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_success:
- codeclimate-test-reporter < coverage/lcov.info
- ckeditor5-dev-tests-save-revision
env:
  global:
  - secure: mrYun71A5k7UeyTllgUJHgfdjFjW7UuHzpb7hYew9tGYMrd0IHnHWR7flwKK9PPmgD8oOsIcgMt6KSQ4PI8usI/uRO/7ti2y4WNSjpueG/n8WuXvQOWUjHrt3TLGjGwS3ia7fTBJ2Mgbg8a4MYHCpzakxGx5yo6qJ4ZoVOCrFUNTEmuKpErzXp6lBMQCb7eCkuvXfNDlOFZIbhfdZB/1LsPOBF6Pht8fMGIFHKoqwRotC996zIphyROUW4kP0JjMSKXtQBk4KR+4Dl7fMgsaXCxM4Seho615GpAyIYtUmQxowOOXPyWfFmnp9v+lF6noQGm5DC2EUUtN+FMQ1USNT9Q1RfAjKxVCAau40jAdqR7Qfo75/QY+YgTOCchK/r/8PlfImv395GDMRzVviKrXOPsQ57CDcvlTejsNkITUM9BL2dA2k6sSRfEhz9JXmoJ6ASljUUTeSLQ4U9VwksQztFeV1W5RtDNnS2KzrlqS/DoHLTRPlxNR55rYvecBjQ2GP3eKAU19xZCpPipmCDUrcMvWtZjcUctBuWjzeOXGQRzyW1DGPoKjSOXWSDLBJKJSzxCSKBNEQlSfegi7kxnw7b/QcvAsWT8V54f9YroMppP6phwn6G/ekg8M1RFXK3Fp1K6IC8OF+NdwqlfAHnSMxUN4tGmPj2CglLK5GMQJcSk=
  - secure: atyGwyKpDB647Se5jZOsUgo7OWIxotnrxd/CvgUxtA0Msgmf0hGPyg1sLUeDeigcLw0Je7DmbAWfPCnMSawCvjFaOxBeO8dZo4IBHiadEWLdDWSPmq6IqWnPWzp0t1hJdcDRPv3xBCqVWiMJRJaIzeB6QPGK40G0ozSbEqGzVPzt62kivqKIC2ALwSsQXs6SZ/8CMW0C7RvOyt71FULWqK8BkrUvRP/zQWjERt/pp4E4YNYCYkB95Rixv8e87iu5Usaz05pT4LfWGM9Pue5d8Y0ptyHJ6Txgz4arugwakznfmvznWfjoyw4SNuE+eDB7p8OOwcVvo8ErG+cJpxLbR11/NTTRW9gHmINb7RvjiGdu4lA9gaNj/zkSVE2GgQ90SfcopKR9pgakSOKu/l7BQTZcoa8Y/EPFFuidWqd7YUHRxNd9E/3zEHKuf7npmj0/LM3EuSGEfprs17n8EeygwojYZVliZw8sHUo0Nmqr8QJl58lqMO3hVZunIUg19pl09ZpUctzpCM0PqZBlq843wvAU1tmdwyzocgFShYQ6hTE5jFC38qhfyQf6jrCd87ksOrJm4rK8zyCzoD6iycNAAGbjxfPLvcSKEImli+CihPrRBQps/0vkjuUyU72LVA51fnNCsu/u+OXxrULumERh/2NUD3hlG8RRKx5gN+xx9yk=
