sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "6"
cache:
  - node_modules
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install mgit2 lerna
  - npm install git://github.com/ckeditor/ckeditor5-dev.git#t/mgit-tests
  - cd node_modules/ckeditor5-dev/packages/ckeditor5-dev-tests && npm install && npm link
  - cd $TRAVIS_BUILD_DIR && npm link @ckeditor/ckeditor5-dev-tests
  - npm install gulp @ckeditor/ckeditor5-dev-lint
script:
  - node_modules/.bin/ckeditor5-dev-tests-travis
